# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "IRaf Blog"
weight = 1
[ru]
languageName = "Russian"
languagedirection = "ltr"
title = "IRaf блог"
weight = 2